### ISSUE TITLE
Does download option work?

### ISSUE THREAD

**Issue by LustForLove** [aslushnikov/latex-online#34]
And another little question... Does `download=sample.pdf` option work?

`latexonline.cc/compile?git=https://github.com/aslushnikov/diplom-latex&target=diplom.tex&download=sample.pdf`

still gives me `compile.pdf` in the end. Or I've made smth wrong? Sorry then.

**Comment by aslushnikov** [comment]
Thanks @LustForLove, this is fixed now.

**Comment by LustForLove** [comment]
Well, thank you! Works fine for me. Little QoL suggestion: with this option it still shows "LatexOnline is compiling..." on that page. I was confused for a second. But I see you wanna report compilation process related things later on. Just consider message for this case! Thanks again.

**Comment by aslushnikov** [comment]
@LustForLove oh right, thanks. We'll fix this later on
